services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - mongo-data:/data/db

    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - mongodb
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    
    environment:
      - VITE_API_BASE_URL=http://34.204.192.5:5000/api

    depends_on:
      - backend
    networks:
      - app-network


volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge










