name: this is a test file
on:
  push:
    
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Display a simple hello Akash Message
        run: echo "Hello Akash from ${{runner.os}}"
